[[themes]]
name = "tokyonight_night"
[themes.palette]
foreground = "#c0caf5"
black = "#15161e"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#a9b1d6"
bright_black = "#414868"
bright_red = "#f7768e"
bright_green = "#9ece6a"
bright_yellow = "#e0af68"
bright_blue = "#7aa2f7"
bright_magenta = "#bb9af7"
bright_cyan = "#7dcfff"
bright_white = "#c0caf5"
[themes.component_style]
playback_metadata = { fg = "White", modifiers = ["Dim"] }
playlist_desc = { fg = "Cyan", modifiers = ["Dim"] }
playback_progress_bar = { fg = "BrightGreen", modifiers = ["Bold"] }
playback_progress_bar_unfilled = { fg = "BrightBlack" }

    
[[themes]]
name = "tokyonight_moon"
[themes.palette]
background = "#222436"
foreground = "#c8d3f5"
black = "#1b1d2b"
red = "#ff757f"
green = "#c3e88d"
yellow = "#ffc777"
blue = "#82aaff"
magenta = "#c099ff"
cyan = "#86e1fc"
white = "#828bb8"
bright_black = "#444a73"
bright_red = "#ff757f"
bright_green = "#c3e88d"
bright_yellow = "#ffc777"
bright_blue = "#82aaff"
bright_magenta = "#c099ff"
bright_cyan = "#86e1fc"
bright_white = "#c8d3f5"
    
